version: '3.8'

services:
  consumir-api:
    image: consumir-api:latest
    build:
      context: ./ConsumirApi
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - pessoas-api

  pessoas-api:
    image: pessoas-api:latest
    build:
      context: ./PessoasApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"